### ISSUE TITLE
All mailbox sizes show as 0

### ISSUE THREAD

**Issue by aplayer67** [microsoft/FastTrack#90]
[Question]
Hi,

I've ran the script against 14k users, it's produced the output files but the Find-MailboxDelegates-Schedule.csv file has all of the mailboxes reported as 0 (MB), everything else seems to be working.

If I run the commands that collect this information in the script by themselves it returns the correct value. I haven't modified the script in any way.

This is the command I used to execute the script:

.\Find-MailboxDelegates.ps1 -InputMailboxesCSV "C:\Temp\InputMailboxs.csv" -FullAccess -SendAs -SendOnBehalfTo -Calendar -EnumerateGroups

Thanks

Andrew

**Comment by soyalejolopez** [comment]
Hi Andrew,

Thank you for bringing this up. Do you see any exception/error in the log file when the script is trying to pull the mailbox sizes?

Thanks!

From: aplayer67 ***@***.***>
Sent: Thursday, April 1, 2021 8:10 AM
To: microsoft/FastTrack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/FastTrack] All mailbox sizes show as 0 (#90)


[Question]
Hi,

I've ran the script against 14k users, it's produced the output files but the Find-MailboxDelegates-Schedule.csv file has all of the mailboxes reported as 0 (MB), everything else seems to be working.

If I run the commands that collect this information in the script by themselves it returns the correct value. I haven't modified the script in any way.

This is the command I used to execute the script:

.\Find-MailboxDelegates.ps1 -InputMailboxesCSV "C:\Temp\InputMailboxs.csv" -FullAccess -SendAs -SendOnBehalfTo -Calendar -EnumerateGroups

Thanks

Andrew

-

**Comment by aplayer67** [comment]
No, but  I'm going to change the way I've been running it to see if it helps with the results.

**Comment by soyalejolopez** [comment]
Okay. Also, are you running it in the exchange console from the server or remote powershell?

**Comment by aplayer67** [comment]
Directly on the Exchange server.

Looking at the help it seems I need to run it once to create the permissions file and then a second time to create the batches?

Will that then populate the mailbox sizes?

**Comment by soyalejolopez** [comment]
The script only needs to run once. During that run it'll execute 3 key steps - the collection of permissions, the batching of permissions, and the creation of the schedule file. 

The schedule file is really more of an extra that we did as part of our FastTrack migrations in order to get certain metadata that would be helpful for migrations, e.g. mailbox size. We can troubleshoot what you're seeing, but would likely need to see the outputs and log file to investigate further. The other option is you can leverage the output of Step #2 (that's really the key output from the script) and then use that as input to capture the mailbox sizes separately. 

We have a the following guidance here on how you can analyze those permissions by using the output of Step #2. See here for more details: https://aka.ms/permissions-analysis . Hope this helps.

**Comment by dwhitney7** [comment]
Please let us know if there are any further questions or concerns.
