### ISSUE TITLE
Script does not search for contacts folder sharing

### ISSUE THREAD

**Issue by GitHubUser010** [microsoft/FastTrack#95]
Hello, thank you for this script, it's great. It appears though that the script does not search for contacts folder sharing.  I'm not sure if the contacts folder sharing was left out on purpose because maybe it doesn't commonly cause issues for Exchange Online migrations?  However I was able to add contacts folder sharing support to the script fairly easily by copying/pasting the calendar folder code and calendar folder variables and changing that new pasted code to support the contacts folder.  Not sure if you want to add support for the contacts folder to the official script but that might be helpful for some.  The contacts folder is commonly shared by users due to the "share contacts" function in Outlook.

thank you

**Comment by dwhitney7** [comment]
Thanks for the feedback! From what we've typically seen, contacts folder sharing has not been a blocker to hybrid migrations, either because of minimal use or simply because calendar, etc, permissions would have also been shared and so the script would already keep them together. That said, we welcome forks and pull requests to add functionality or clarifications.

Regards,
David

**Comment by GitHubUser010** [comment]
thanks so much for the quick and clear feedback on this.  Our environment might be somewhat unique to the frequency of users using the contacts sharing Outlook function without other delegation or contact sharing, but do understand your point.  thanks again for the great script, this will be useful for us long term as well because we'll need to pull back mailboxes on-prem for separated employees due to our use of the archive mailbox feature and the licensing that's required in EO for mailboxes with them.
